### ISSUE TITLE
Plotting rashba spin splitting using QE

### ISSUE THREAD

**Issue by aktariitkgp** [romerogroup/pyprocar#155] opened 2024-07-17 05:58 UTC
Dear developer
  I am interested to use pyprocar for Plotting rashba spin splitting using QE. But the given example has used VASP data.We got expectation value of sx,sy,sz in QE for non-colinear case but how to use them to get spin texture in pyprocar. Could you guide me to get this done ?

**Comment by lllangWV** [comment] 2024-07-18 19:59
Hello,

Thank you for following the steps to calculate the expectation values of sx, sy, and sz for non-collinear cases. You can use the sample code provided in the PyProcar documentation for further analysis. Here's the link to the specific example that might help you: [PyProcar Rashba Spin Splitting Example](https://romerogroup.github.io/pyprocar/examples/03-fermi2d/plot_rashba_spin_spliting.html#sphx-glr-examples-03-fermi2d-plot-rashba-spin-spliting-py).

To apply this to your case, ensure you set the `code` parameter to 'qe'. Below is an example configuration that you might find useful:

```python
pyprocar.fermi2D(
    code='qe',  # Specify the code used
    dirname=data_dir,  # Directory containing your data
    energy=-0.90,  # Energy level to analyze
    fermi=-1.1904,  # Fermi energy level
    spin_texture=True,  # Enable spin texture plotting
    spin_projection='x',  # Axis for spin projection
    arrow_size=3,  # Size of the arrows in the plot
    arrow_density=6,  # Density of the arrows
    plot_color_bar=True  # Include a color bar in the plot
)
```

I hope this helps! Let me know if you need further assistance.

Best regards,

Logan Lang

**Comment by ahromero** [comment] 2024-07-18 20:01
I just want to stress that PyProcar assumes that you have successfully created the files required to perform the analysis. If your question is more related to how the DFT package does it, I think this question should be answered by the developers of the particular DFT code.


______________________________________::::__________________________________________
Prof. Aldo Humberto Romero
Director Research Computing, West Virginia University
Eberly Family Distinguished Professor
Fellow American Physical Society
Editor Physica B, Assistant Editor EPJB, Editor Frontiers in Physics
Section Editor Papers in Physics
Member of the Editorial Board of  “Materials” and “Symmetry Physics”
https://scholar.google.com/citations?user=pwte-hQAAAAJ&hl=en

Physics and Astronomy Department
West Virginia University
135 Willey Street, PO Box 6315
111 White Hall
Morgantown, WV 26506
Phone:  304-293-6317
Fax:  304-293-5732
email: ***@***.***


From: Logan Lang ***@***.***>
Date: Thursday, July 18, 2024 at 3:59 PM
To: romerogroup/pyprocar ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [romerogroup/pyprocar] Plotting rashba spin splitting using QE (Issue #155)

Hello,

Thank you for following the steps to calculate the expectation values of sx, sy, and sz for non-collinear cases. You can use the sample code provided in the PyProcar documentation for further analysis. Here's the link to the specific example that might help you: PyProcar Rashba Spin Splitting Example<https://romerogroup.github.io/pyprocar/examples/03-fermi2d/plot_rashba_spin_spliting.html#sphx-glr-examples-03-fermi2d-plot-rashba-spin-spliting-py>.

To apply this to your case, ensure you set the code parameter to 'qe'. Below is an example configuration that you might find useful:

pyprocar.fermi2D(

    code='qe',  # Specify the code used

    dirname=data_dir,  # Directory containing your data

    energy=-0.90,  # Energy level to analyze

    fermi=-1.1904,  # Fermi energy level

    spin_texture=True,  # Enable spin texture plotting

    spin_projection='x',  # Axis for spin projection

    arrow_size=3,  # Size of the arrows in the plot

    arrow_density=6,  # Density of the arrows

    plot_color_bar=True  # Include a color bar in the plot

)

I hope this helps! Let me know if you need further assistance.

Best regards,

Logan Lang

**Comment by aktariitkgp** [comment] 2024-07-20 05:31
Hi,
thank you for your reply.I have tried rashba spin texture plotting of  BiSb monolayer from QE DFT data. But I am not getting arrow like spin texture. I am attaching the Quantum Espresso input, output file and also the pyprocar command with output.Could you please help me to solve this problem .
Best Regards
Aktar
[BiSb_rashba_plotting.zip](https://github.com/user-attachments/files/16318941/BiSb_rashba_plotting.zip)
[qe_plot_rashba_spin_splitting.pdf](https://github.com/user-attachments/files/16318943/qe_plot_rashba_spin_splitting.pdf)

**Comment by lllangWV** [comment] 2024-07-20 15:49
Hey, do you have atomic_proj.xml file? 

This is needed to get the spin projections. Usually it is found in {outdir}/BiSb.save/atomic_proj.xml

Logan Lang

**Comment by aktariitkgp** [comment] 2024-07-20 16:43
thank you for your reply.
Yes I have copied that to the main directory but output of pyprocar has not been change.Still I am not getting the spin texture. 
best regards
Aktar

**Comment by lllangWV** [comment] 2024-07-20 16:46
Can you print the top portion of the file?

It should look like this. Note the ATOMIC_SIGMA_PHI tags.

```xml
<PROJECTIONS>
  <HEADER NUMBER_OF_BANDS="24" NUMBER_OF_K-POINTS="288" NUMBER_OF_SPIN_COMPONENTS="1" NUMBER_OF_ATOMIC_WFC="20" NUMBER_OF_ELECTRONS="16.0000000000000" FERMI_ENERGY="1.32696224169585"/>
  <EIGENSTATES>
    <K-POINT Weight="2.370370370370369E-003">
   3.333333333333328E-02   3.333333333333328E-02  -3.333333333333328E-02
    </K-POINT>
    <E>
  -5.152171009613084E+00  -4.936188461244900E+00  -2.639636836406888E+00
  -2.637801417016428E+00  -2.637801414321328E+00  -2.429217066793234E+00
  -2.427126190230954E+00  -2.427126186334162E+00   7.293343299511922E-01
   7.399093077600304E-01   1.154309062587640E+00   1.154309125618879E+00
   1.170996464182533E+00   1.246317812929362E+00   1.246317818654533E+00
   1.310184084560468E+00   1.310184157458412E+00   1.329399731602361E+00
   1.464067662966760E+00   1.464067667738217E+00   3.038050304751674E+00
   3.038050448503952E+00   3.042334655012764E+00   3.042334785566284E+00
    </E>
    <PROJS>
      <ATOMIC_WFC index="1" spin="1">
  4.020728075520062E-009  1.744683946096106E-010
 -0.322842302341005       0.905916726445155     
 -1.292075644682044E-009  1.884965520070510E-008
  5.567429825008905E-009  3.856875787153329E-009
 -9.932995331679635E-009  6.186142324839088E-009
 -2.032415807079354E-003 -8.625531468468776E-003
 -1.007943728481564E-013  2.216768435481242E-013
  2.533362025367025E-009  1.121530960115913E-008
 -1.169911594713840E-006 -1.793923702023082E-006
  0.122447825173354       0.244932985001097     
  1.647307698000085E-006 -1.664445760092443E-006
  2.970437322662738E-007 -1.320337095838056E-006
 -1.809688604699368E-007 -1.758783150689091E-006
  8.458772010080151E-008 -6.256882412590012E-008
  2.541360183414085E-008  5.478109711477257E-008
 -4.175397860795016E-009  1.380028199354788E-009
 -1.082745004765684E-013  1.153840911705117E-012
  1.453344461378982E-003 -1.506582759179797E-004
  8.499916152870934E-010  9.541745903812737E-009
  1.170522012650110E-013  3.193413415647495E-013
  1.628658888308543E-009  5.076122189251464E-009
  7.175032443185181E-011  1.862690557352664E-011
 -1.603052739081878E-007  1.009862838988738E-009
  5.520516993578117E-008  6.846308485841006E-008
      </ATOMIC_WFC>
      <ATOMIC_SIGMA_PHI index="1" ipol="1">
  0.709740752637302      -0.650980237377313     
 -2.113909180756610E-009 -4.457786065312494E-009
 -5.283841007896077E-003 -6.061548571308209E-003
  8.055439815191079E-009 -1.462727975201639E-009
  4.257705299437475E-013  4.419173360581397E-013
  1.395670740009049E-008  8.634524132018378E-009
  1.005485224579885E-008  3.701708455211800E-009
 -5.244272337182433E-009 -3.311617044148325E-009
 -0.263235798597621      -5.542171977526718E-002
 -2.012715348807446E-006 -6.710318192921760E-007
  1.463107413002263E-012  1.348044283621883E-011
 -4.042294651784850E-009 -6.389151901986523E-009
 -2.108414073779248E-003 -1.715005593499600E-003
 -5.394365509836518E-013  3.310046681193057E-012
  1.276082642678866E-008  4.661784122790558E-009
  4.492776759455099E-007 -8.926966836788266E-007
 -5.938798272275430E-007 -1.626716990027712E-006
  8.652184269206063E-007 -1.065345328577195E-006
 -2.513941106289774E-008 -2.103116217391370E-008
  3.565538799827027E-008  4.409905314651006E-008
 -6.757441848383893E-008 -3.473717375929126E-008
 -1.180520915771332E-007  7.030853566838621E-008
 -8.494914494061589E-011  1.932305704333004E-010
  4.697274486042957E-009  4.031682956234794E-010
      </ATOMIC_SIGMA_PHI>
      <ATOMIC_SIGMA_PHI index="1" ipol="2">
  0.650980237377313       0.709740752637302     
  4.457785506240578E-009 -2.113909381695070E-009
  6.061548571308209E-003 -5.283841007896077E-003
  1.462727975201639E-009  8.055439815191079E-009
 -4.419173360581397E-013  4.257705299437475E-013
 -8.634524180874173E-009  1.395670741828870E-008
 -3.701708430771312E-009  1.005485225305634E-008
  3.311617029494725E-009 -5.244272402821556E-009
  5.542171977526718E-002 -0.263235798597621     
  6.710318191853302E-007 -2.012715348753545E-006
 -1.348044283621883E-011  1.463107413002263E-012
  6.389151901986523E-009 -4.042294651784850E-009
  1.715005593499600E-003 -2.108414073779248E-003
 -3.310046681193057E-012 -5.394365509836518E-013
 -4.661784122790558E-009  1.276082642678866E-008
  8.926966836804147E-007  4.492776759366615E-007
  1.626716990024697E-006 -5.938798272330831E-007
  1.065345328576884E-006  8.652184269298766E-007
  2.103116218722761E-008 -2.513941107233532E-008
 -4.409905314511718E-008  3.565538799575162E-008
  3.473717376001632E-008 -6.757441848434038E-008
 -7.030853566791187E-008 -1.180520915772874E-007
 -1.932305704333004E-010 -8.494914494061589E-011
 -4.031682947561177E-010  4.697274486042957E-009
      </ATOMIC_SIGMA_PHI>
      <ATOMIC_SIGMA_PHI index="1" ipol="3">
 -4.020728514843256E-009 -1.744679938321401E-010
  0.322842302341005      -0.905916726445155     
  1.292075605528586E-009 -1.884965523571562E-008
 -5.567429813163206E-009 -3.856875720947619E-009
  9.932995352415207E-009 -6.186142339676854E-009
  2.032415807079354E-003  8.625531468468776E-003
  1.007943728481564E-013 -2.216768435481242E-013
 -2.533362025367025E-009 -1.121530960115913E-008
  1.169911594827956E-006  1.793923702046666E-006
 -0.122447825173354      -0.244932985001097     
 -1.647307698003851E-006  1.664445760097527E-006
 -2.970437322670765E-007  1.320337095829001E-006
  1.809688604766596E-007  1.758783150696193E-006
 -8.458772009839289E-008  6.256882412745533E-008
 -2.541360185015614E-008 -5.478109711181875E-008
  4.175397860795016E-009 -1.380028199354788E-009
  1.082745004765684E-013 -1.153840911705117E-012
 -1.453344461378982E-003  1.506582759179797E-004
 -8.499916152870934E-010 -9.541745903812737E-009
 -1.170522012650110E-013 -3.193413415647495E-013
 -1.628658888308543E-009 -5.076122189251464E-009
 -7.175032443185181E-011 -1.862690557352664E-011
  1.603052739078287E-007 -1.009862839070053E-009
 -5.520516993618097E-008 -6.846308485841006E-008
      </ATOMIC_SIGMA_PHI>
```

**Comment by aktariitkgp** [comment] 2024-07-20 17:06
<PROJECTIONS>
  <HEADER NUMBER_OF_BANDS="38" NUMBER_OF_K-POINTS="4" NUMBER_OF_SPIN_COMPONENTS="1" NUMBER_OF_ATOMIC_WFC="36" NUMBER_OF_ELECTRONS="30.000000000000000" FER
MI_ENERGY="-2.1459480593841361E-002"/>
  <EIGENSTATES>
    <K-POINT Weight="6.2500000000000000E-002">
   0.000000000000000E+00   0.000000000000000E+00   0.000000000000000E+00
    </K-POINT>
    <E>
  -2.204472707830746E+00  -2.204472707830744E+00  -2.202592233862350E+00
  -2.202592233862348E+00  -2.113749660399898E+00  -2.113749660399896E+00
  -2.112177159804366E+00  -2.112177159804364E+00  -2.111173632480816E+00
  -2.111173632480816E+00  -1.811303335259598E+00  -1.811303335259598E+00
  -1.810047213132093E+00  -1.810047213132090E+00  -1.592603636000624E+00
  -1.592603636000623E+00  -1.591087530854529E+00  -1.591087530854528E+00
  -1.590488362002856E+00  -1.590488362002853E+00  -9.316401684523452E-01
  -9.316401684523452E-01  -5.937255504279242E-01  -5.937255504279214E-01
  -1.691705022238004E-01  -1.691705022238004E-01  -7.104752926275495E-02
  -7.104752926275359E-02  -3.295596570496744E-02  -3.295596570496608E-02
  -9.618521366176745E-03  -9.618521366163056E-03   9.484303639698156E-02
   9.484303639698705E-02   1.658940168043031E-01   1.658940168043524E-01
   2.123365264549456E-01   2.123365264560074E-01
    </E>
    <PROJS>
      <ATOMIC_WFC index="1" spin="1">
  -7.1451870458077299E-008   8.5891799515673550E-008
  -5.3017468366889364E-009  -2.4691011894176912E-007
   4.5656361411664653E-004   4.4519443302415418E-004
  -1.8272516800127599E-004   2.5146379524082062E-005
   3.6382396681604832E-004   1.2452173191035767E-004
  -3.5198763686353218E-004  -1.5003908481900190E-004
   1.1353705086161736E-007  -1.4646809654321122E-007
  -2.2639238507222298E-007  -1.3508224286492773E-007
   5.0392736617392575E-004   8.4248709155121740E-004
  -8.7885234465638271E-004  -2.1090211813340259E-004
  -2.0008054857877100E-007  -7.8609476635536912E-008
  -1.3309037848185934E-007  -3.1749038152846520E-008
  -1.2552365978443780E-004  -1.4600018164588266E-004
  -1.4920451538837729E-003  -1.4860049165239114E-004
   5.7023305163248677E-004   3.9812881574242563E-004
  -2.3432215438233539E-006  -9.0435853943015079E-005
   1.0134140235491806E-007  -4.0926597582105484E-007
   5.1729171667057663E-007   3.8167954173780327E-007
   2.1003707562319302E-003   1.4597559324383558E-003
   2.1884671654416252E-004   1.1470737184787420E-003
  -7.9353587593592161E-003  -7.6766175363221972E-002
  0.37494772060212817       0.41301309881548554     
  0.12042781480924561       0.24553534840976571     
  0.44147896760580441       0.49079028144707026     
  0.15422190832067778        1.2477547475993271E-002
  0.11499948742670918        7.0662705856503027E-002
   6.9775594081406656E-002  -1.7080142798475018E-002
  -3.9728463579016556E-002  -1.2528796619226887E-002
  -6.0103154446711216E-006   7.6481822100515906E-006
   1.8197196043540087E-005   7.7268649973719072E-006
 -0.22615122691263545       -7.6851545271743441E-002
  0.19409547951611980        4.4943999302197321E-002
  -4.8296076094619375E-002 -0.10139655179339857     
  -6.5292289388875491E-002  -5.5116691922896199E-002
   9.9571117607999415E-008  -4.1206429595569416E-007
  -9.0253933257566921E-007  -3.1367471527918300E-006
   9.8894428052708414E-003  -2.2707570498504720E-002
  -1.4451115793778087E-002  -2.2886327143888510E-002
      </ATOMIC_WFC>
      <ATOMIC_WFC index="2" spin="1">
   3.8857955065446648E-009   2.4694241493317115E-007
   7.4594693331986317E-008   8.3195518372873589E-008
   8.7284464080848376E-005  -1.6248769005399724E-004
  -2.5804726746477859E-004  -5.8314665438911201E-004
   1.7553382021231936E-004   3.3999249339458637E-004
   1.5095665032229238E-004   3.5367447438451952E-004
  -6.1001689808000414E-008  -2.5648921589578599E-007
   1.7379184495723912E-007  -6.4368942517736144E-008
  -2.4248941454955292E-004  -8.7066643067639990E-004
  -8.6012874264651193E-004  -4.7318690660119300E-004
   1.2405817051332896E-007   5.7683596796278408E-008
  -2.0571281766391947E-007  -6.2529078991013787E-008
   3.7553324559628717E-004   1.4516389444419291E-003
  -1.6351429357645657E-004  -1.0166274593673141E-004
  -8.0853700072818814E-005   4.0580951022724243E-005
  -6.1998792039625857E-004  -3.1509881219441045E-004
  -4.1799097622117337E-007  -4.8841991213272040E-007
  -4.0084903904849534E-007   1.3062811509909067E-007
   3.5648905923161330E-004   1.1120195697187345E-003
   1.1462668290151412E-003  -2.2865950796418563E-003
 -0.34021536465463648       0.44206234700595060     
  -1.6831501797774226E-003   7.7156870177787606E-002
  -4.3676157239096451E-002 -0.65868898003100562     
   9.1915213238969479E-002  0.25756952372359398     
   2.0984578413942759E-002  0.13333322003191039     
   4.7811585301803898E-002 -0.14715345217755244     
  -3.5994321822938782E-002   2.0969747693406364E-002
  -7.1823991787154318E-002  -1.2957900340278203E-003
   1.9396855005904268E-005   3.8219387960836126E-006
   6.7999409163188584E-007   9.7035279660595553E-006
  0.19473272601099051        4.2097301257659113E-002
  0.23733273799207208        2.6901851931095046E-002
   1.7236424900601465E-002   8.3688936713468068E-002
  -6.6013892744329977E-002  -9.0862191976965767E-002
   2.3478230679191414E-006   2.2695295560110768E-006
  -4.1059154608485277E-007  -1.0391615436200485E-007
   2.3571756274942061E-002   1.3303661773610389E-002
  -2.2191703935025120E-002   1.0998422794386384E-002
      </ATOMIC_WFC>
      <ATOMIC_WFC index="3" spin="1">
  -3.1662147355338011E-007  -2.7261578401660547E-007
  -1.7045633094597834E-007  -4.3261276177000707E-007
   2.5835966861630492E-003   2.5194238309256887E-003
  -1.0341835551938589E-003   1.4273003889978333E-004
  -3.8525353620132846E-004  -1.3197850353684204E-004
   3.7257729707016948E-004   1.5868925345893792E-004
  -1.2989115863969170E-007   1.2293336291600496E-007
   1.3206920231978274E-007   5.5195296873832012E-008
  -3.5687880102354928E-004  -5.9662769575343291E-004
   6.2239292423215938E-004   1.4936836689375017E-004
  -6.9284352660604030E-007   1.8089463340144676E-007
  -2.7287933930097291E-007  -3.5207334855413136E-007
  -5.2913677312835120E-004  -6.1610368411456557E-004
  -6.2926404312361869E-003  -6.2666200695750407E-004
  -2.9585502448579767E-002  -2.0654878802280653E-002
   1.1361063907319637E-004   4.7033669811546198E-003
  -1.5413377195058753E-006   3.9919211445010178E-007
  -2.4646537873096452E-006  -8.6900697545549965E-007
  -1.5550525923473706E-002  -1.0807923793760284E-002
  -1.6205251534111738E-003  -8.4908163479259745E-003
   1.9100972916927320E-003   1.8476258783624553E-002
  -9.0230543593560017E-002  -9.9390953657178940E-002
   2.3173142041988601E-002   4.7248831979105455E-002
   8.4967928454766889E-002   9.4457920989242647E-002
  0.42162373992833857        3.4118246789156925E-002
  0.31439893746844910       0.19317763344737318     
  -9.2400843534564681E-003   2.2590464463502248E-003
   5.2720285524934934E-003   1.6576651056660410E-003
   1.5837425207651523E-005  -2.2507039281062513E-005
  -4.8051484467084848E-005  -2.6977096049804472E-005
  0.47094902129355420       0.16004241345036180     
 -0.40421662787611767       -9.3595603202119015E-002
 -0.15582255838748130      -0.32712754586728132     
 -0.21063064481960073      -0.17781820763769440     
   5.6025897406941638E-006  -5.3600146641755164E-006
  -2.8293787177960383E-006  -1.8719260338612154E-006
   9.6293089344665767E-003  -2.2114703280639931E-002
  -1.4072505543284935E-002  -2.2289743395537943E-002
      </ATOMIC_WFC>

**Comment by aktariitkgp** [comment] 2024-07-20 17:07
<PROJECTIONS>
  <HEADER NUMBER_OF_BANDS="38" NUMBER_OF_K-POINTS="4" NUMBER_OF_SPIN_COMPONENTS="1" NUMBER_OF_ATOMIC_WFC="36" NUMBER_OF_ELECTRONS="30.000000000000000" FER
MI_ENERGY="-2.1459480593841361E-002"/>
  <EIGENSTATES>
    <K-POINT Weight="6.2500000000000000E-002">
   0.000000000000000E+00   0.000000000000000E+00   0.000000000000000E+00
    </K-POINT>
    <E>
  -2.204472707830746E+00  -2.204472707830744E+00  -2.202592233862350E+00
  -2.202592233862348E+00  -2.113749660399898E+00  -2.113749660399896E+00
  -2.112177159804366E+00  -2.112177159804364E+00  -2.111173632480816E+00
  -2.111173632480816E+00  -1.811303335259598E+00  -1.811303335259598E+00
  -1.810047213132093E+00  -1.810047213132090E+00  -1.592603636000624E+00
  -1.592603636000623E+00  -1.591087530854529E+00  -1.591087530854528E+00
  -1.590488362002856E+00  -1.590488362002853E+00  -9.316401684523452E-01
  -9.316401684523452E-01  -5.937255504279242E-01  -5.937255504279214E-01
  -1.691705022238004E-01  -1.691705022238004E-01  -7.104752926275495E-02
  -7.104752926275359E-02  -3.295596570496744E-02  -3.295596570496608E-02
  -9.618521366176745E-03  -9.618521366163056E-03   9.484303639698156E-02
   9.484303639698705E-02   1.658940168043031E-01   1.658940168043524E-01
   2.123365264549456E-01   2.123365264560074E-01
    </E>
    <PROJS>
      <ATOMIC_WFC index="1" spin="1">
  -7.1451870458077299E-008   8.5891799515673550E-008
  -5.3017468366889364E-009  -2.4691011894176912E-007
   4.5656361411664653E-004   4.4519443302415418E-004
  -1.8272516800127599E-004   2.5146379524082062E-005
   3.6382396681604832E-004   1.2452173191035767E-004
  -3.5198763686353218E-004  -1.5003908481900190E-004
   1.1353705086161736E-007  -1.4646809654321122E-007
  -2.2639238507222298E-007  -1.3508224286492773E-007
   5.0392736617392575E-004   8.4248709155121740E-004
  -8.7885234465638271E-004  -2.1090211813340259E-004
  -2.0008054857877100E-007  -7.8609476635536912E-008
  -1.3309037848185934E-007  -3.1749038152846520E-008
  -1.2552365978443780E-004  -1.4600018164588266E-004
  -1.4920451538837729E-003  -1.4860049165239114E-004
   5.7023305163248677E-004   3.9812881574242563E-004
  -2.3432215438233539E-006  -9.0435853943015079E-005
   1.0134140235491806E-007  -4.0926597582105484E-007
   5.1729171667057663E-007   3.8167954173780327E-007
   2.1003707562319302E-003   1.4597559324383558E-003
   2.1884671654416252E-004   1.1470737184787420E-003
  -7.9353587593592161E-003  -7.6766175363221972E-002
  0.37494772060212817       0.41301309881548554     
  0.12042781480924561       0.24553534840976571     
  0.44147896760580441       0.49079028144707026     
  0.15422190832067778        1.2477547475993271E-002
  0.11499948742670918        7.0662705856503027E-002
   6.9775594081406656E-002  -1.7080142798475018E-002
  -3.9728463579016556E-002  -1.2528796619226887E-002
  -6.0103154446711216E-006   7.6481822100515906E-006
   1.8197196043540087E-005   7.7268649973719072E-006
 -0.22615122691263545       -7.6851545271743441E-002
  0.19409547951611980        4.4943999302197321E-002
  -4.8296076094619375E-002 -0.10139655179339857     
  -6.5292289388875491E-002  -5.5116691922896199E-002
   9.9571117607999415E-008  -4.1206429595569416E-007
  -9.0253933257566921E-007  -3.1367471527918300E-006
   9.8894428052708414E-003  -2.2707570498504720E-002
  -1.4451115793778087E-002  -2.2886327143888510E-002
      </ATOMIC_WFC>
      <ATOMIC_WFC index="2" spin="1">
   3.8857955065446648E-009   2.4694241493317115E-007
   7.4594693331986317E-008   8.3195518372873589E-008
   8.7284464080848376E-005  -1.6248769005399724E-004
  -2.5804726746477859E-004  -5.8314665438911201E-004
   1.7553382021231936E-004   3.3999249339458637E-004
   1.5095665032229238E-004   3.5367447438451952E-004
  -6.1001689808000414E-008  -2.5648921589578599E-007
   1.7379184495723912E-007  -6.4368942517736144E-008
  -2.4248941454955292E-004  -8.7066643067639990E-004
  -8.6012874264651193E-004  -4.7318690660119300E-004
   1.2405817051332896E-007   5.7683596796278408E-008
  -2.0571281766391947E-007  -6.2529078991013787E-008
   3.7553324559628717E-004   1.4516389444419291E-003
  -1.6351429357645657E-004  -1.0166274593673141E-004
  -8.0853700072818814E-005   4.0580951022724243E-005
  -6.1998792039625857E-004  -3.1509881219441045E-004
  -4.1799097622117337E-007  -4.8841991213272040E-007
  -4.0084903904849534E-007   1.3062811509909067E-007
   3.5648905923161330E-004   1.1120195697187345E-003
   1.1462668290151412E-003  -2.2865950796418563E-003
 -0.34021536465463648       0.44206234700595060     
  -1.6831501797774226E-003   7.7156870177787606E-002
  -4.3676157239096451E-002 -0.65868898003100562     
   9.1915213238969479E-002  0.25756952372359398     
   2.0984578413942759E-002  0.13333322003191039     
   4.7811585301803898E-002 -0.14715345217755244     
  -3.5994321822938782E-002   2.0969747693406364E-002
  -7.1823991787154318E-002  -1.2957900340278203E-003
   1.9396855005904268E-005   3.8219387960836126E-006
   6.7999409163188584E-007   9.7035279660595553E-006
  0.19473272601099051        4.2097301257659113E-002
  0.23733273799207208        2.6901851931095046E-002
   1.7236424900601465E-002   8.3688936713468068E-002
  -6.6013892744329977E-002  -9.0862191976965767E-002
   2.3478230679191414E-006   2.2695295560110768E-006
  -4.1059154608485277E-007  -1.0391615436200485E-007
   2.3571756274942061E-002   1.3303661773610389E-002
  -2.2191703935025120E-002   1.0998422794386384E-002
      </ATOMIC_WFC>
      <ATOMIC_WFC index="3" spin="1">
  -3.1662147355338011E-007  -2.7261578401660547E-007
  -1.7045633094597834E-007  -4.3261276177000707E-007
   2.5835966861630492E-003   2.5194238309256887E-003
  -1.0341835551938589E-003   1.4273003889978333E-004
  -3.8525353620132846E-004  -1.3197850353684204E-004
   3.7257729707016948E-004   1.5868925345893792E-004
  -1.2989115863969170E-007   1.2293336291600496E-007
   1.3206920231978274E-007   5.5195296873832012E-008
  -3.5687880102354928E-004  -5.9662769575343291E-004
   6.2239292423215938E-004   1.4936836689375017E-004
  -6.9284352660604030E-007   1.8089463340144676E-007
  -2.7287933930097291E-007  -3.5207334855413136E-007
  -5.2913677312835120E-004  -6.1610368411456557E-004
  -6.2926404312361869E-003  -6.2666200695750407E-004
  -2.9585502448579767E-002  -2.0654878802280653E-002
   1.1361063907319637E-004   4.7033669811546198E-003
  -1.5413377195058753E-006   3.9919211445010178E-007
  -2.4646537873096452E-006  -8.6900697545549965E-007
  -1.5550525923473706E-002  -1.0807923793760284E-002
  -1.6205251534111738E-003  -8.4908163479259745E-003
   1.9100972916927320E-003   1.8476258783624553E-002
  -9.0230543593560017E-002  -9.9390953657178940E-002
   2.3173142041988601E-002   4.7248831979105455E-002
   8.4967928454766889E-002   9.4457920989242647E-002
  0.42162373992833857        3.4118246789156925E-002
  0.31439893746844910       0.19317763344737318     
  -9.2400843534564681E-003   2.2590464463502248E-003
   5.2720285524934934E-003   1.6576651056660410E-003
   1.5837425207651523E-005  -2.2507039281062513E-005
  -4.8051484467084848E-005  -2.6977096049804472E-005
  0.47094902129355420       0.16004241345036180     
 -0.40421662787611767       -9.3595603202119015E-002
 -0.15582255838748130      -0.32712754586728132     
 -0.21063064481960073      -0.17781820763769440     
   5.6025897406941638E-006  -5.3600146641755164E-006
  -2.8293787177960383E-006  -1.8719260338612154E-006
   9.6293089344665767E-003  -2.2114703280639931E-002
  -1.4072505543284935E-002  -2.2289743395537943E-002
      </ATOMIC_WFC>

**Comment by lllangWV** [comment] 2024-07-20 17:11
Wait, this is your atomic_proj.xml file. It has no xml tags?

**Comment by aktariitkgp** [comment] 2024-07-20 17:15
![Screenshot from 2024-07-20 22-44-44](https://github.com/user-attachments/assets/fdb24198-0735-400a-9b41-1db6895f3fa4)

**Comment by lllangWV** [comment] 2024-07-20 17:18
Do you see ATOMIC_SIGMA_PHI tag? It should be under the ATOMIC_WFC tag

**Comment by aktariitkgp** [comment] 2024-07-20 17:19
there is no ATOMIC_SIGMA_PHI tag

**Comment by ahromero** [comment] 2024-07-20 17:25
Did you try to repeat the same calculation in the tutorial? The same version?  Then compare with your new calculation, number of files, run success, etc.  if the problem remains, please contact us, with a full description of the problem. Sorry we can not take all requests. We are working on our own research as well so

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lllangWV** [comment] 2024-07-20 17:32
I see what the issue is now. The base version of Quantum ESPRESSO does not compute the orbital-resolved spin projection components. To address this, we collaborated with a Quantum ESPRESSO developer who created a special branch to include these calculations. This branch, however, has not been merged into the main branch.

You can find the installation instructions for this branch in our [QE DFT Prep documentation](https://romerogroup.github.io/pyprocar/dftprep/qe.html), specifically under the section "Magnetic Calculations for Non-Collinear Systems." Please note that this branch does not receive regular updates, so it should be used cautiously.

In the meantime, non-collinear calculations are still feasible with Quantum ESPRESSO, but without the specific spin components and the orbitals are represented in the total angular momentum (coupled) basis.

Here are the steps to install the special branch:

```bash
git clone git@gitlab.com:pietrodelugas/q-e.git
cd q-e
git checkout new_proj
# Follow the installation instructions for the package.
# Set your PATH to include the bin directory inside the cloned repository.
```

Maybe in the furture we can ask the Quantum ESPRESSO developers to integrate this feature into a future release permanently.

Logan Lang

**Comment by aktariitkgp** [comment] 2024-07-20 18:41
thank you for your guidance and valuable time. Now I can plot the spin texture. I was making a mistake as you have mentioned.


Aktar

**Comment by ahromero** [comment] 2024-07-20 18:43
Excellent… thanks for your understanding… we can not keep up with the number of users, we try as much as we can…


______________________________________::::__________________________________________
Prof. Aldo Humberto Romero
Director Research Computing, West Virginia University
Eberly Family Distinguished Professor
Fellow American Physical Society
Editor Physica B, Assistant Editor EPJB, Editor Frontiers in Physics
Section Editor Papers in Physics
Member of the Editorial Board of  “Materials” and “Symmetry Physics”
https://scholar.google.com/citations?user=pwte-hQAAAAJ&hl=en

Physics and Astronomy Department
West Virginia University
135 Willey Street, PO Box 6315
111 White Hall
Morgantown, WV 26506
Phone:  304-293-6317
Fax:  304-293-5732
email: ***@***.***


From: Aktar ***@***.***>
Date: Saturday, July 20, 2024 at 2:42 PM
To: romerogroup/pyprocar ***@***.***>
Cc: Aldo Romero ***@***.***>, Comment ***@***.***>
Subject: Re: [romerogroup/pyprocar] Plotting rashba spin splitting using QE (Issue #155)

thank you for your guidance and valuable time. Now I can plot the spin texture. I was making a mistake as you have mentioned.

Aktar

**Closed** 2024-07-25 14:47 UTC
